#!/usr/bin/env python3
import argparse
from virtualenv_relocator.cmd import make_environment_relocatable


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(dest="virtualenv_dir")
    return parser.parse_args()


def main():
    args = parse_args()
    make_environment_relocatable(args.virtualenv_dir)


if __name__ == "__main__":
    main()
